### ISSUE TITLE
Remove "samples" folder from package

### ISSUE THREAD

**Issue by jmdacruz** [mcafee/mvision-edr-activity-feed#41]
We are currently adding the `samples` folder into the package, which results in the addition of a top-level `samples` module in Python when installing our module. This causes confusion, because the top-level package will always shadow the local `samples` folder. For example, if I modify one of the samples in the local folder (e.g., `samples.individual`), and then try to load the modified module, I'll still be using the previous version that is now installed in my Python module directory. Another example is adding a new local sample on the `samples` folder (e.g., `samples/foobar.py`) and then trying to load this module: This will fail because the global `samples` folder will override the local one, and the new file is not available on the global module (this happened to #40).

**Comment by paguerre2** [comment]
[AS DESIGNED] confusion isn't relevant as the samples is intended to explain in simple code how to achieve te goal of subscribing to entities.
