### ISSUE TITLE
Consumer timeout parameter not available on the CLI

### ISSUE THREAD

**Issue by jmdacruz** [mcafee/mvision-edr-activity-feed#42]
We are currently ignoring the `--consumer-timeout` parameter. We need to map this to the [`session_timeout`](https://github.com/opendxl/opendxl-streaming-client-python/blob/master/dxlstreamingclient/channel.py#L171) on the OpenDXL SDK

**Comment by paguerre2** [comment]
[AS DESIGNEd] This is an improvement not an issue as by default kafka uses common settings if not speciefied.
